# Generated by Django 2.1 on 2018-08-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20180816_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpanelentry',
            old_name='is_valid',
            new_name='valid',
        ),
        migrations.RenameField(
            model_name='flagattemptentry',
            old_name='is_sharing',
            new_name='sharing',
        ),
        migrations.RenameField(
            model_name='flagattemptentry',
            old_name='is_valid',
            new_name='valid',
        ),
        migrations.RemoveField(
            model_name='adminpanelentry',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='auditentry',
            name='ip',
        ),
        migrations.AddField(
            model_name='logentry',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
