# Generated by Django 2.1 on 2018-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0002_auto_20180822_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='uid',
        ),
        migrations.AlterField(
            model_name='team',
            name='invite',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
