# Generated by Django 2.1 on 2018-08-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0002_auto_20180815_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(default=4678245244459, unique=True),
        ),
    ]
