# Generated by Django 2.1 on 2018-08-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0003_auto_20180815_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(default=9974548082679, unique=True),
        ),
    ]
