# Generated by Django 2.1 on 2018-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0001_initial'),
        ('teamboard', '0003_auto_20180822_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='banned',
        ),
        migrations.AddField(
            model_name='team',
            name='not_banned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='solved_tasks',
            field=models.ManyToManyField(to='adminboard.Task'),
        ),
    ]
