# Generated by Django 2.1 on 2018-08-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0004_auto_20180816_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(default=6023475884726, unique=True),
        ),
    ]
