# Generated by Django 2.1 on 2018-08-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0005_auto_20180816_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(default=8009259406131, unique=True),
        ),
    ]
