# Generated by Django 2.1 on 2018-08-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0006_auto_20180816_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(default=8848644111715, unique=True),
        ),
    ]
