# Generated by Django 2.1 on 2018-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0007_auto_20180816_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(default=8042200345498, unique=True),
        ),
    ]
