# Generated by Django 2.1 on 2018-08-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamboard', '0009_auto_20180816_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
