# Generated by Django 2.1 on 2018-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
                ('flag', models.CharField(default='CTF{F1@G}', max_length=50, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(db_index=True, to='adminboard.Tag')),
            ],
        ),
    ]
