# Generated by Django 2.1 on 2018-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.TextField(default='CTF{F1@G}', unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
