# Generated by Django 2.1 on 2018-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0002_auto_20180822_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='adminboard.Tag'),
        ),
    ]
