# Generated by Django 2.1 on 2018-08-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0003_auto_20180815_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
